# Generated by Django 4.2.1 on 2023-05-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseTable',
            fields=[
                ('idx', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('jibun', models.CharField(max_length=100, null=True)),
                ('jungong', models.DateField()),
                ('houseType', models.CharField(max_length=10)),
                ('floors', models.SmallIntegerField()),
                ('housePrice', models.IntegerField(null=True)),
                ('monthlyPrice', models.IntegerField(null=True)),
                ('memePrice', models.IntegerField(null=True)),
                ('currentlyUpdate', models.DateTimeField()),
                ('firstUpdate', models.DateTimeField()),
                ('recommend', models.BooleanField()),
                ('agentName', models.CharField(max_length=100)),
                ('agentAddress', models.CharField(max_length=100)),
                ('agentNumber', models.CharField(max_length=100)),
            ],
        ),
    ]
