# Generated by Django 4.2.1 on 2023-05-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_housetable_currentlyupdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housetable',
            name='latitude',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='housetable',
            name='longtitude',
            field=models.CharField(default='', max_length=30),
        ),
    ]
