# Generated by Django 4.2.1 on 2023-06-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_housetable_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilteringHousetTable',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('jibun', models.CharField(max_length=100, null=True)),
                ('jungong', models.CharField(max_length=50)),
                ('houseType', models.CharField(max_length=10)),
                ('floors', models.SmallIntegerField()),
                ('housePrice', models.IntegerField(null=True)),
                ('monthlyPrice', models.IntegerField(null=True)),
                ('memePrice', models.IntegerField(null=True)),
                ('currentlyUpdate', models.CharField(max_length=50)),
                ('firstUpdate', models.CharField(max_length=50)),
                ('recommend', models.BooleanField()),
                ('agentName', models.CharField(max_length=100)),
                ('agentAddress', models.CharField(max_length=100)),
                ('agentNumber', models.CharField(max_length=100)),
                ('latitude', models.CharField(default='', max_length=30)),
                ('longtitude', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
